language: generic
sudo: required
services:
  - docker


before_install:
  - docker build -t praveenkuber/docker-react -f Dockerfile.dev .
  
script:
  - docker run praveenkuber/docker-react npm run test -- --coverage
